services:
  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile.dev
    container_name: portfolio-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_HOST=0.0.0.0
      - NODE_ENV=development
    stdin_open: true
    tty: true
    networks:
      - portfolio-network

  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile.dev
    container_name: portfolio-api-dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - ENVIRONMENT=development
      - CORS_ORIGINS=http://localhost:5173
      - DATABASE_URL=postgresql://portfolio_user:portfolio_pass@postgres:5432/portfolio
    networks:
      - portfolio-network
    depends_on:
      - frontend

  postgres:
    image: postgres:17
    container_name: portfolio-db-dev
    restart: always
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: portfolio_user
      POSTGRES_PASSWORD: portfolio_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

volumes:
  postgres_data: